---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flasker
  template:
    metadata:
      labels:
        app: flasker
    spec:
      containers:
      - name: flasker
        image: hub.freshmail.pl/spinnaker/flasker
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flasker-nodeport
spec:
  type: NodePort
  selector:
    app: flasker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
